### ISSUE TITLE
My(Pain-in-the-ass)QL

### ISSUE THREAD

**Issue by bhanson248** [yuriy1337/Lunch-Randomizer#10]
Can we set up a MySQL user specifically for this project?  I have a different root password on my dev server and it is going to be the cause of a few minor headaches in the future if we don't.

**Comment by yuriy1337** [comment]
I agree, we should have a separate MySQL user not root anyway, and all of my servers have different login anyway so it is a pain. This should be done in the restructure.

**Comment by yuriy1337** [comment]
no longer applicable, closing
