### ISSUE TITLE
Add navigation to every page

### ISSUE THREAD

**Issue by yuriy1337** [yuriy1337/Lunch-Randomizer#15]
If clicked on a link, navigation disappears.

**Comment by tomarra** [comment]
Agreed. This should be part of the layout.

**Comment by yuriy1337** [comment]
Good, I'll take care of it then.

**Comment by tomarra** [comment]
If you change or add to the en.yml you need to make the same changes in the pirate.yml so they stay in sync. You also have to come up with good pirate strings :)

**Comment by yuriy1337** [comment]
Why do we need multiple languages support?

**Comment by tomarra** [comment]
1. It's good coding practice
2. Just in case we have to later on
3. You know pirate would be an awesome language setting
