### ISSUE TITLE
Implement user log in/out

### ISSUE THREAD

**Issue by tomarra** [yuriy1337/Lunch-Randomizer#18]
Need to be able to let users log in and out easier. I think a username/password field that just a AJAX login in the header of the page would be great.

**Comment by adamkiczula** [comment]
Having the login in the header makes sense, I'm not sure if using AJAX does though, the entire page will change in some cases, it is probably best to redirect to the same URL, just with the session now in place.

**Comment by yuriy1337** [comment]
How about a Log In link that overlays the login fields on top, and then logged in with AJAX? (similar to reddit login, but better styling and maybe some animation)

**Comment by yuriy1337** [comment]
Is this still an issue?
