### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by yuriy1337** [yuriy1337/Lunch-Randomizer#20]
A logo for our lunch randomizer would be nice.

**Comment by yuriy1337** [comment]
Adam, could you see if you can come up with anything?

**Comment by adamkiczula** [comment]
We have 2 design people in this group, why on earth would you pick me as the
logo designer?
On Apr 13, 2011 3:48 PM, "yuriy1337" <
reply@reply.github.com>
wrote:

**Comment by yuriy1337** [comment]
They are "design" people, only because they know Photoshop. I'm sure you know it too, plus they are working on other stuff. If you don't want to, thats fine.

**Comment by adamkiczula** [comment]
Actually, I don't really know photoshop. They have more experience creating
logos than any of us, which is why I would think they would be better suited
for it. That, and I don't have a creative bone in my body.

**Comment by yuriy1337** [comment]
I wanted you to feel included...

**Comment by tomarra** [comment]
Assigning to Pat.

**Comment by yuriy1337** [comment]
Test: ![LOL](http://aphrodite.cooltext.com/rendered/cooltext528378470.png)

Cool it works. Ignore this. ^

**Comment by adamkiczula** [comment]
My attempt at your logo Yuriy... let me know what you think... http://i.imgur.com/JDHUa.png

**Comment by tomarra** [comment]
Pat made one. I need to download it and put it in the project. I would also like to get the .psd file checked in too if he has one.

**Comment by yuriy1337** [comment]
I spoke with Pat, he mentioned that you also have a "Lunch Randomizer" text logo. (Just some fancier text) I wanted to put that in also. That is what I meant originally by logo.
