### ISSUE TITLE
Workspace restructure

### ISSUE THREAD

**Issue by tomarra** [yuriy1337/Lunch-Randomizer#24]
Need to move everything we have into a rails folder and add a resources folder. This can contain things like ER models, Photoshop files, etc.

**Comment by tomarra** [comment]
Talked to Adam about this. Initially he said put it in the doc folder. I think only the things needed on the box should go into the rails project. Keep everything else in a separate folder in the workspace.

**Comment by yuriy1337** [comment]
but it will still be checked in right? How exactly do you want to structure this?

**Comment by tomarra** [comment]
Everything should be checked in. I think the top level of the workspace has two folders rails, and resources. Rails would contain the app itself and everything needed for deployment. Resources would contain anything that relates to the app that is not needed for deployment.

**Comment by yuriy1337** [comment]
Sounds good, approved.
