### ISSUE TITLE
Error loading layout

### ISSUE THREAD

**Issue by yuriy1337** [yuriy1337/Lunch-Randomizer#43]
I get this with RubyMine and Netbeans with a new checkout from github. Something broke. Does anyone know what it is?

C:\Ruby192\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:/Users/Yuriy/Documents/Projects/Lunch-Randomizer/rails/script/rails server -b 127.0.0.1 -p 3000 -e development
=> Booting WEBrick
=> Rails 3.0.5 application starting in development on http://127.0.0.1:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2011-04-19 19:25:29] INFO  WEBrick 1.3.1
[2011-04-19 19:25:29] INFO  ruby 1.9.2 (2010-08-18) [i386-mingw32]
[2011-04-19 19:25:29] INFO  WEBrick::HTTPServer#start: pid=5908 port=3000

Started GET "/" for 127.0.0.1 at 2011-04-19 19:25:43 -0500
  Processing by ApplicationController#index as HTML
Rendered application/index.erb within layouts/application (42.0ms)
Completed   in 55ms

ActionView::Template::Error (syntax error on line 9, col 4: `    list: "List"
'):
    1: <!DOCTYPE html>

```
2: <html>

3: <head>

4:   <title><%= t('.site_title')%></title>

5:   <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>

6:   <%= javascript_include_tag :defaults, :cache => true %>

7:   <%= javascript_include_tag 'jquery-ui' %>
```

  app/views/layouts/application.html.erb:4:in `_app_views_layouts_application_html_erb___782914621_37606776_593015581'

Rendered C:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.0ms)
Rendered C:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (2.0ms)
Rendered C:/Ruby192/lib/ruby/gems/1.9.1/gems/actionpack-3.0.5/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (15.0ms)

**Comment by tomarra** [comment]
It's some kind of error in the strings file. Looking at it now.

**Comment by yuriy1337** [comment]
Wow, really, a space? But white space shouldn't matter. And how did it work before? Because it didn't break earlier.

**Comment by tomarra** [comment]
YAML is very picky on its formatting, white space matters.

"Whitespace indentation is used to denote structure; however tab characters are never allowed as indentation."

http://en.wikipedia.org/wiki/YAML#Syntax

**Comment by yuriy1337** [comment]
huh never knew that. good to know
