### ISSUE TITLE
Restructure the workspace

### ISSUE THREAD

**Issue by tomarra** [yuriy1337/Lunch-Randomizer#6]
Need to clean things up. This looks like a good article on the way things should be organized.

http://net.tutsplus.com/tutorials/php/organize-your-next-php-project-the-right-way/

**Comment by tomarra** [comment]
This is somewhat related to [Issue 5](https://github.com/yuriy1337/Lunch-Randomizer/issues#issue/5).

**Comment by yuriy1337** [comment]
hmm the link isn't available here...

**Comment by tomarra** [comment]
Updated original description with link.

**Comment by tomarra** [comment]
Closing this as we moved to Rails.
