### ISSUE TITLE
Add database script to workspace

### ISSUE THREAD

**Issue by tomarra** [yuriy1337/Lunch-Randomizer#7]
We need a file that defines the database. Just a text file with SQL would be fine.

**Comment by yuriy1337** [comment]
I know, but we can't do a straight dump, since it will contain passwords.

**Comment by tomarra** [comment]
A data dump is not needed. Just the SQL to create the tables so other people (like me) can setup an environment without having to read the code looking for the table and column names.

**Comment by yuriy1337** [comment]
I know. Its on our list. Sorry. Get it at work tomorrow

**Comment by yuriy1337** [comment]
Chu248 added createNew.php
it contains everything needed to create a new db. we should keep that file updated when we update the db.

**Comment by bhanson248** [comment]
Added in the admin folder.  It will delete the current database and create a new one that is empty except for a few locations and categories.  How do you close an issue?

**Comment by yuriy1337** [comment]
Just curious, you do not see the "Comment and Close" button next to the "Comment" Button?

**Comment by bhanson248** [comment]
All I see is "Comment"  Must need admin or something.

**Comment by yuriy1337** [comment]
Alright try now. I can close it, but we all should be able to.

**Comment by bhanson248** [comment]
Success!

**Comment by yuriy1337** [comment]
Excellent.
