### ISSUE TITLE
Create Groups

### ISSUE THREAD

**Issue by yuriy1337** [yuriy1337/Lunch-Randomizer#8]
We should allow multiple people to use this. Create groups, and each group will have users, categories, and lunch-menu options. This way anyone can set up a lunch randomizer for their workplace.

**Comment by swanny0819** [comment]
I need to start studying how to use Ruby, but I can work on the design.

**Comment by yuriy1337** [comment]
Okay, assigning this to you. This is a pretty good way to start. I will email you some stuff to read.

**Comment by tomarra** [comment]
This is the book developers on this project should be learning Rails with, http://pragprog.com/titles/rails4/agile-web-development-with-rails

Note that it a huge update to the original Agile Rails book. The 4th edition was a complete rewrite for Rails 3. Things read in the 3rd edition or earlier may not work or there may be a much better way of doing things.

**Comment by yuriy1337** [comment]
Oh yeah, I have that one too. I meant to send that one. Ill email it.

**Comment by adamkiczula** [comment]
I know Pat was working on design, but I was thinking about it and figured I would put down my thoughts. Below are tables and columns that would be added for the groups feature. Let me know what you guys think, or if you have any suggestions for improvement let me know.

groups_users
- group_id
- user_id
- is_group_admin

groups
- label
- location

selections
- group_id

groups_places
- group_id
- place_id

**Comment by yuriy1337** [comment]
The way I saw it is that users should be able to join groups, if they have a group "key". 

Why not a groups_selections that?

Also we might need a groups_categories or do we want that to be global? I think it should be per group.

**Comment by adamkiczula** [comment]
I'm not sure what you mean by group "key"...
groups_selections is 1:*, there is a chance that it would be *:* (e.g. 2 groups have the same selection on the same day) but since it is unlikely that it will happen, the space lost to the repeating entries is well worth saving the hassle of making it a many to many.

Groups do have categories through places, category is an attribute of a place not a group. Unless you are trying to label groups as "American" and "Mexican" in which case you sir are a racist.

**Comment by yuriy1337** [comment]
lmao no, I was saying a lunch group category... Okay I see what you mean. 
Are we going to be storing all the previous selections for a group?
By key I was thinking we could generate a unique key for each group and that user can give out that key and when others register, they can put in that key and automatically join that group.
